// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const BRANCH_LIST = 'BRANCH_LIST';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const SERVICE_LIST = 'SERVICE_LIST';
export const BRANCH_EDIT_DATA = 'BRANCH_EDIT_DATA';
export const PRODUCT_EDIT_DATA = 'PRODUCT_EDIT_DATA';
export const SERVICE_EDIT_DATA = 'SERVICE_EDIT_DATA';
export const PACKAGE_LIST = 'PACKAGE_LIST';
export const PACKAGE_EDIT_DATA= "PACKAGE_EDIT_DATA";
export const SUPERADMIN_DASHBOARD_DATA= "SUPERADMIN_DASHBOARD_DATA";
export const SAVED = 'SAVED';
export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const BOOKING_LIST = 'BOOKING_LIST';

export const BOOKING_LIST_PLACED = 'BOOKING_LIST_PLACED';
export const BOOKING_LIST_ASSIGNED = 'BOOKING_LIST_ASSIGNED';
export const BOOKING_LIST_COMPLETED = 'BOOKING_LIST_COMPLETED';
export const BOOKING_LIST_CANCELLED = 'BOOKING_LIST_CANCELLED';

export const REPORT_LIST_COMPLETED = 'REPORT_LIST_COMPLETED';
export const REPORT_LIST_CANCELLED = 'REPORT_LIST_CANCELLED';
export const REPORT_BRANCH_WISE = 'REPORT_BRANCH_WISE';

export const SALES_REPORT = 'SALES_REPORT';



//Auth const

/////Staff Module ////////

export const STAFF_LIST ="STAFF_LIST";
export const STAFF_EDIT_DATA="STAFF_EDIT_DATA";
export const ROOM_DATA="ROOM_DATA";
export const ROOM_EDIT_DATA="ROOM_EDIT_DATA";
export const LEAVE_DATA="LEAVE_DATA";
export const LEAVE_EDIT_DATA="LEAVE_EDIT_DATA";
/////////// End /////////

export const SIGNUP_USER = 'SIGNUP_USER';
export const RECEIVE_OTP = 'RECEIVE_OTP';

export const NEWTIMESLOT = 'NEWTIMESLOT';

export const TIMESLOTLIST = 'TIMESLOTLIST';
export const SERVICE_PACKAGE_LIST = 'SERVICE_PACKAGE_LIST';
export const TIMESLOTS_DATA = 'TIMESLOTS_DATA';


export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const UPDATE_LOAD_USER = 'UPDATE_LOAD_USER';

